version: '2'
services:
  disk-api:
    container_name: disk-api
    build: 
      context: .
      dockerfile: ./src/Api/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:80"
    volumes:
      - /opt/disk/appsettings.api.json:/app/appsettings.Production.json

  disk-ui:
    container_name: disk-ui
    build: 
      context: .
      dockerfile: ./src/Ui/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
    volumes:
      - /opt/disk/appsettings.ui.json:/app/appsettings.Production.json